### ISSUE TITLE
Image export incomplete (missing styles)

### ISSUE THREAD

**Issue by spyro2000** [bumbeishvili/org-chart#127]
**Describe the bug**
Loving this lib :)
But when I export the image, the image seems not complete (not all CSS styles seems to be taken into account)

**To Reproduce**
1. Create chart
2. Apply some styling like this: `h1 {background-color: gray;}` (same for DIV borders etc.)
3. Export as PNG

**Expected behavior**
Exported image should look like in the browser

**Screenshots**

Browser:

![image](https://user-images.githubusercontent.com/8479925/157012046-28119b1e-d577-4046-a508-63838322e2c1.png)

Export:

![image](https://user-images.githubusercontent.com/8479925/157012172-1463724e-1414-424f-a8e2-3d0d6f695f63.png)

**Full scss markup**

```scss
div.node {
    background-color: white;
    border-radius:10px;
    border: 1px solid lightgray;
    padding: 0 $s $s $s;
    max-height: 455px;
    overflow: auto;

    h1 {
      font-size: $md;
      margin: 0 (-$s) $s (-$s);
      align-content: center;
      text-align: center;
      background-color: whitesmoke;
      border-top-left-radius: $s;
      border-top-right-radius: $s;
      padding: $xs;
    }

    table {
      border-collapse: collapse;

      tr {

        &:not(:first-child).category {
          border-top: 1px solid lightgray;
        }

        &.odd {
          background-color: white;
        }

        &.even {
          background-color: whitesmoke;
        }

        &.category {

          td {
            padding-top: $s;
            padding-bottom: $xs;
          }

          td:first-child {
            font-weight: bold;
          }

        }
      }

      ul {
        padding: 0 0 $xs;
        margin: 0 0 0 $md;
      }

    }

  }
````

**Desktop (please complete the following information):**
 - OS: Win10x64
 - Browser: Chrome 98.0.4758.102 
 - Org-Chart: 2.6.0
 - d3: 7.3
