### ISSUE TITLE
Coordinates of the edge endpoints...

### ISSUE THREAD

**Issue by seimic** [bumbeishvili/org-chart#348]
Hi,

first of all, thanks for providing this library. It's pretty cool and easy to use. :)

Could anyone point me to the solution to find out the coordinates of the ends of the edges? Or at least from which direction
they are attached to a node in a graph. I would like to display small badges with additional short labels at the end of the edges
like in the screenshot below. Alternatively same like the child-count button directly at the node.

![image](https://github.com/bumbeishvili/org-chart/assets/34323525/061b56cb-0d2b-4f5d-bdc0-317884f9a769)

Thanks,
Michael

**Comment by bumbeishvili** [comment]
Hi, there are some helper properties attached which might help with determining direction

in `nodeContent` you are receiving `node` argument

• If that node has a `node.children` property then the link is connecting from the top
• If that node does not have a `children` property and `node.compactEven ` is true then the link is connecting from the right side
• If that node does not have a `children` property and `node.compactEven ` is  false then link is connecting from right side

**Comment by seimic** [comment]
Ahh cool. Thanks, this helps. I give it a try. I'm using it with angular and attach the node components (in nodeUpdate) in a container created before in nodeContent. That fits fine, I can pass the additional information to the container to render the badges.

**Comment by kanth609** [comment]
@seimic Hey hi, did you get a chance to implement this? Possible to share some reference?

**Comment by seimic** [comment]
Hi,

I decided finally to solve it without to care for the edges at all and placing the badges at top left corner of the node components. Looks like this:
![image](https://github.com/bumbeishvili/org-chart/assets/34323525/f38e9461-b0d1-4227-a0b8-3ed48e382d4c)
(Just for the record... this are fictive companies here, no real data)

But if you like the other way, it works as described by [bumbeishvili](https://github.com/bumbeishvili).
If you detect the direction from which the edge is coming, you only need to place the badges above or
right from the incoming edges.
Assuming your badges are within the node component its basically something like this in css:

```css
--badge-width: 60px;
--badge-height: 1.5em;
--badge-distance: 0.4em;

.chart-node-badge-top {
  position: absolute;
  top: calc(-1 * (var(--badge-distance) + var(--badge-height)));
  left: calc(50% + var(--badge-distance));
}

.chart-node-badge-left {
  position: absolute;
  top: calc(50% - var(--badge-height) - var(--badge-distance)); 
  left: calc(-1 * (var(--badge-width) + var(--badge-distance)));
}
  
.chart-node-badge-right {
  position: absolute;
  top: calc(50% - var(--badge-height) - var(--badge-distance)); 
  right: calc(-1 * (var(--badge-width) + var(--badge-distance)));
}
```

Kind regards
Michael
